{
  "MonsterType": {
    "1": "Demon",
    "2": "Beast",
    "3": "Human",
    "4": "Undead"
  },
  "Element": {
    "0": "Physical",
    "1": "Fire",
    "2": "Lightning",
    "3": "Cold",
    "4": "Poison",
    "5": "Arcane",
    "6": "Holy"
  },
  "Resource": {
    "0": "Mana",
    "1": "Arcanum",
    "2": "Fury",
    "3": "Spirit",
    "5": "Hatred",
    "6": "Discipline",
    "7": "Faith"
  },
  "ResourceX": {
    "witchdoctor": "Mana",
    "wizard": "Arcane Power",
    "barbarian": "Fury",
    "monk": "Spirit",
    "demonhunter": "Hatred",
    "crusader": "Wrath"
  },
  "AffixFix": {
    "0": "Wizard_DiamondSkin/Script Formula 39", // Defense
    "10": "Barbarian_Leap_OLD/Physical Damage Min", // Strength
    "34": "1xx_Superior Armor Def 6",
    "35": "1xx_Superior Armor",
    "50": "1xx_Gold VIII Secondary",
    "57": "X1_Monk_MantraOfHealing_v2/Script Formula 2", // Level
    "60": "1xx_MF IX Secondary",
    "71": "1xx_FurySetPoint I",
    "73": "1xx_WrathHeals 12 Two-Handed",
    "77": "1xx_Experience XIII",
    "82": "1xx_HealthGlobeChance I",
    "86": "1xx_HealthGlobeBonus 16",
    "93": "21x_ArcaneResist X",
    "96": "21x_ResistAll VIII",
    "102": "Wizard_MagicMissile_Speed/Projectile Speed", // Skill_Total
    "126": "21x_Regen 19 Secondary",
    "134": "1xx_Life VI Secondary",
    "150": "X1_MaxWrath 6 Legendary",
    "156": "X1_WrathRegen 14 Two-Handed",
    "168": "1xx_Run 6",
    "187": "zolt_Tablet_stateChange/Attack Speed", // Casting_Speed_Total
    "192": "1xx_Superior Weapon Speed 6",
    "194": "1xx_Kings XI",
    "198": "ZombieFemale_Projectile/Attack Speed", // Attacks_Per_Second_Total
    "200": "1xx_Haste 10 Secondary",
    "207": "X1_CooldownReduction 6 Secondary",
    "209": "BareHandedPassive/Generic Buff Attribute 1 And Parameter", // Damage_Delta
    "211": "BareHandedPassive/Generic Buff Attribute 0 And Parameter", // Damage_Min
    "226": "1xx_Superior Weapon MaxDmg 6",
    "234": "1xx_Superior Weapon MinDmg 6",
    "237": "1xx_Superior Weapon 7",
    "238": "1xx_Damage VI",
    "241": "1xx_DamageBonusPhysical 4",
    "245": "1xx_CriticalChance VIII Secondary",
    "250": "1xx_Superior Weapon Crit Dmg 6",
    "260": "1xx_Block 11 Secondary",
    "331": "21x_Thorns 16 Secondary",
    "335": "1xx_LifeS 11 Two-Handed",
    "337": "1xx_HitMana 12",
    "340": "1xx_KillMana 12",
    "341": "1xx_ArcanePowerOnCrit 6",
    "342": "21x_HitLife 15 Two-Handed",
    "343": "21x_KillLife 15 Two-Handed",
    "381": "1xx_Sockets Bracer V",
    "677": "X1_Wizard_Wormhole/Script Formula 7", // Rune_A
    "678": "X1_WickerMan_FirePhantom/RuneE Proc Scalar", // Rune_B
    "679": "X1_Monk_Epiphany/Script Formula 30", // Rune_C
    "680": "X1_Monk_MantraOfRetribution_v2/Script Formula 23", // Rune_D
    "681": "X1_SpectralHound_Buff/Script Formula 13", // Rune_E
    "682": "1xx_ResistStun 1",
    "684": "1xx_ResistRoot 1",
    "686": "1xx_ResistFreeze 1",
    "688": "1xx_ResistStunRootFreeze 1",
    "689": "1xx_CCReduction 8",
    "722": "X1_ResourceCostReduction 6 Secondary",
    "1053": "1xx_GoldPickUpRadius 7",
    "1056": "Trait_Barbarian_Fury/Fury Gained Per Percent Health Lost", // Resource_Gain_Bonus_Percent
    "1094": "1xx_HitFear 12",
    "1095": "1xx_HitStun 12",
    "1096": "1xx_HitBlind 12",
    "1097": "1xx_HitFreeze 12",
    "1098": "1xx_HitChill 12",
    "1099": "1xx_HitSlow 12",
    "1100": "1xx_HitImmobilize 12",
    "1101": "1xx_HitKnockback 12",
    "1105": "1xx_DefenseMissile 5",
    "1106": "1xx_DefenseMelee 5",
    "1108": "1xx_DamReductionVsElite 5",
    "1109": "1xx_DamageReductionArcane 9",
    "1110": "1xx_DamageVsMonsterTypeHuman 6",
    "1111": "1xx_DamageVsElite 5 Secondary",
    "1117": "1xx_WeaponHitFear2h 12",
    "1118": "1xx_WeaponHitStun2h 12",
    "1119": "1xx_WeaponHitBlind2h 12",
    "1120": "1xx_WeaponHitFreeze2h 12",
    "1121": "1xx_WeaponHitChill2h 12",
    "1122": "1xx_WeaponHitSlow2h 12",
    "1123": "1xx_WeaponHitImmobilize2h 12",
    "1124": "1xx_WeaponHitKnockback2h 12",
    "1173": "1xx_Skill_Wizard_Blizzard 1",
    "1185": "1xx_PrimaryAttribute_Str 17 Two-Handed Legendary",
    "1186": "1xx_PrimaryAttribute_Dex 17 Two-Handed Legendary",
    "1187": "1xx_PrimaryAttribute_Int 17 Two-Handed Legendary",
    "1188": "1xx_PrimaryAttribute_Vit 17 Legendary",
    "1189": "1xx_REQ 19",
    "1192": "1xx_Indestructible 2",
    "1270": "x1_ProcPower_ReapersWraps",
    "1297": "1xx_BindOnEquip",
    "1331": "X1_SplashDamage 6 Secondary",
    "1332": "X1_CrushingBlow 6 Secondary",
    "1377": "X1_Monk_MysticAlly_v2/Script Formula 7" // Effective_Level
  },
  "Affixes": {
    "10": "Strength_Item",
    "11": "Dexterity_Item",
    "12": "Intelligence_Item",
    "13": "Vitality_Item",
    "50": "Gold_Find",
    "60": "Magic_Find",
    "71": "Resource_Set_Point_Bonus#{Resource}",
    "73": "Spending_Resource_Heals_Percent#{Resource}",
    "77": "Experience_Bonus",
    "78": "Experience_Bonus_Percent",
    "82": "Health_Globe_Bonus_Chance",
    "86": "Health_Globe_Bonus_Health",
    "93": "Resistance#{Element}",
    "96": "Resistance_All",
    "126": "Hitpoints_Regen_Per_Second",
    "134": "Hitpoints_Max_Percent_Bonus_Item",
    "150": "Resource_Max_Bonus#{Resource}",
    "156": "Resource_Regen_Per_Second#{Resource}",
    "168": "Movement_Speed",
    "192": "Attacks_Per_Second_Item_Percent",
    "200": "Attacks_Per_Second_Percent",
    "207": "Power_Cooldown_Reduction_Percent_All",
    "209": "Damage#{Element} (pair)$2",
    "211": "Damage#{Element} (pair)$0",
    "219": "Damage#{Element} (pair)$2",
    "226": "Damage_Weapon_Bonus_Delta#{Element}",
    "227": "Damage#{Element} (pair)$2",
    "228": "Damage#{Element} (pair)$0",
    "234": "Damage_Weapon_Bonus_Min#{Element}",
    "235": "Damage#{Element} (pair)$0",
    "237": "Damage_Percent",
    "238": "Damage_Weapon_Percent_Bonus",
    "240": "Damage_Type_Percent_Bonus#{Element}",
    "241": "Damage_Dealt_Percent_Bonus#{Element}",
    "245": "Critical_Chance",
    "250": "Crit_Damage_Percent",
    "260": "Block_Chance_Bonus_Item",
    "331": "Thorns_Fixed#{Element}",
    "335": "Steal_Health_Percent",
    "337": "Resource_On_Hit#{Resource}",
    "340": "Resource_On_Kill#{Resource}",
    "341": "Resource_On_Crit#{Resource}",
    "342": "Hitpoints_On_Hit",
    "343": "Hitpoints_On_Kill",
    "367": "Amplify_Damage_Type_Percent#{Element}",
    "381": "@Sockets ({VALUE})",
    "682": "Resistance_Stun",
    "684": "Resistance_Root",
    "686": "Resistance_Freeze",
    "688": "Resistance_StunRootFreeze",
    "689": "CrowdControl_Reduction",
    "722": "Resource_Cost_Reduction_Percent_All",
    "1053": "Gold_PickUp_Radius",
    "1094": "On_Hit_Fear_Proc_Chance",
    "1095": "On_Hit_Stun_Proc_Chance",
    "1096": "On_Hit_Blind_Proc_Chance",
    "1097": "On_Hit_Freeze_Proc_Chance",
    "1098": "On_Hit_Chill_Proc_Chance",
    "1099": "On_Hit_Slow_Proc_Chance",
    "1100": "On_Hit_Immobilize_Proc_Chance",
    "1101": "On_Hit_Knockback_Proc_Chance",
    "1105": "Damage_Percent_Reduction_From_Ranged",
    "1106": "Damage_Percent_Reduction_From_Melee",
    "1108": "Damage_Percent_Reduction_From_Elites",
    "1109": "Damage_Type_Percent_Reduction#{Element}",
    "1110": "Damage_Percent_Bonus_Vs_Monster_Type#{MonsterType}",
    "1111": "Damage_Percent_Bonus_Vs_Elites",
    "1117": "Weapon_On_Hit_Fear_Proc_Chance",
    "1118": "Weapon_On_Hit_Stun_Proc_Chance",
    "1119": "Weapon_On_Hit_Blind_Proc_Chance",
    "1120": "Weapon_On_Hit_Freeze_Proc_Chance",
    "1121": "Weapon_On_Hit_Chill_Proc_Chance",
    "1122": "Weapon_On_Hit_Slow_Proc_Chance",
    "1123": "Weapon_On_Hit_Immobilize_Proc_Chance",
    "1124": "Weapon_On_Hit_Knockback_Proc_Chance",
    "1125": "Weapon_On_Hit_Bleed_Proc_Chance$1",
    "1126": "Weapon_On_Hit_Bleed_Proc_Chance$2",
    "1127": "Weapon_On_Hit_Bleed_Proc_Chance$3",
    "1128": "Weapon_On_Hit_Percent_Bleed_Proc_Chance$1",
    "1129": "Weapon_On_Hit_Percent_Bleed_Proc_Chance$2",
    "1130": "Weapon_On_Hit_Percent_Bleed_Proc_Chance$3",
    "1173": "&Power_Damage_Percent_Bonus",
    "1175": "&Power_Resource_Reduction",
    "1177": "&Power_Cooldown_Reduction",
    "1185": "Strength_Item",
    "1186": "Dexterity_Item",
    "1187": "Intelligence_Item",
    "1188": "Vitality_Item",
    "1189": "Item_Level_Requirement_Reduction",
    "1190": "Item_Level_Requirement_Override",
    "1192": "Item_Indestructible",
    "1270": "{Power}",
    "1297": "Item_Is_BOE",
    "1331": "Splash_Damage_Effect_Percent",
    "1332": "Crushing_Blow_Chance",
    "1335": "Set_Item_Discount"
  },
  "Secondary": {
    "1053": "Gold_PickUp_Radius",
    "1094": "On_Hit_Fear_Proc_Chance",
    "1095": "On_Hit_Stun_Proc_Chance",
    "1096": "On_Hit_Blind_Proc_Chance",
    "1097": "On_Hit_Freeze_Proc_Chance",
    "1098": "On_Hit_Chill_Proc_Chance",
    "1099": "On_Hit_Slow_Proc_Chance",
    "1100": "On_Hit_Immobilize_Proc_Chance",
    "1101": "On_Hit_Knockback_Proc_Chance",
    "1105": "Damage_Percent_Reduction_From_Ranged",
    "1106": "Damage_Percent_Reduction_From_Melee",
    "1110": "Damage_Percent_Bonus_Vs_Monster_Type#{MonsterType}",
    "1117": "Weapon_On_Hit_Fear_Proc_Chance",
    "1118": "Weapon_On_Hit_Stun_Proc_Chance",
    "1119": "Weapon_On_Hit_Blind_Proc_Chance",
    "1120": "Weapon_On_Hit_Freeze_Proc_Chance",
    "1121": "Weapon_On_Hit_Chill_Proc_Chance",
    "1122": "Weapon_On_Hit_Slow_Proc_Chance",
    "1123": "Weapon_On_Hit_Immobilize_Proc_Chance",
    "1124": "Weapon_On_Hit_Knockback_Proc_Chance",
    "1125": "Weapon_On_Hit_Bleed_Proc_Chance$1",
    "1126": "Weapon_On_Hit_Bleed_Proc_Chance$2",
    "1127": "Weapon_On_Hit_Bleed_Proc_Chance$3",
    "1128": "Weapon_On_Hit_Percent_Bleed_Proc_Chance$1",
    "1129": "Weapon_On_Hit_Percent_Bleed_Proc_Chance$2",
    "1130": "Weapon_On_Hit_Percent_Bleed_Proc_Chance$3",
    "1189": "Item_Level_Requirement_Reduction",
    "1190": "Item_Level_Requirement_Override",
    "1192": "Item_Indestructible",
    "1270": "{Power}",
    "1297": "Item_Is_BOE",
    "1335": "Set_Item_Discount",
    "150": "Resource_Max_Bonus#{Resource}",
    "168": "Movement_Speed",
    "331": "Thorns_Fixed#{Element}",
    "343": "Hitpoints_On_Kill",
    "50": "Gold_Find",
    "60": "Magic_Find",
    "682": "Resistance_Stun",
    "684": "Resistance_Root",
    "686": "Resistance_Freeze",
    "688": "Resistance_StunRootFreeze",
    "689": "CrowdControl_Reduction",
    "77": "Experience_Bonus",
    "78": "Experience_Bonus_Percent",
    "86": "Health_Globe_Bonus_Health",
    "93": "Resistance#{Element}"
  }
}